### ISSUE TITLE
problem with pdfloader

### ISSUE THREAD

**Issue by jmayank23** [sudarshan-koirala/youtube-stuffs#1]
ImportError: cannot import name 'is_directory' from 'PIL._util' (/usr/local/lib/python3.10/dist-packages/PIL/_util.py)

**Comment by sudarshan-koirala** [comment]
hello, did you try installing pypdf ?
Run the following command in the notebook. `pip install pypdf`

**Comment by jmayank23** [comment]
<img width="862" alt="Screen Shot 2023-05-16 at 3 46 48 PM" src="https://github.com/sudarshan-koirala/youtube-stuffs/assets/27727185/c309843f-38e9-4328-9ed8-bbdcc1b4cf18">

**Comment by sudarshan-koirala** [comment]
The problem seems to be related to PIL. Try uninstalling and reinstalling Pillow python package.

**Comment by sudarshan-koirala** [comment]
inactive for almost 2 weeks, hence closed.

**Comment by jaideep11061982** [comment]
@sudarshan-koirala  
Your notebooks are really nice
Do we need key for LANGHCAIN API, if yes which one ? I though langchain dsnt requires any key.
Does Unstructured lib use is paid or free ?

**Comment by sudarshan-koirala** [comment]
@jaideep11061982  If there is LANGCHAIN_API_KEY mentioned then it is langsmith api key which is used for tracing. 
https://smith.langchain.com
